name: Deploy Laravel to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Ensure target directory exists and adjust permissions
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@13.211.228.65 << 'EOF'
          sudo mkdir -p /var/www/super-note
          sudo chown -R ec2-user:ec2-user /var/www/super-note
          sudo chmod -R 777 /var/www/super-note
          exit
          EOF

      - name: Copy files to EC2
        run: |
          scp -r -o StrictHostKeyChecking=no * ec2-user@13.211.228.65:/var/www/super-note
          scp -r -o StrictHostKeyChecking=no .[!.]* ec2-user@13.211.228.65:/var/www/super-note

      - name: Revert ownership to nginx and adjust permissions
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@13.211.228.65 << 'EOF'
          sudo chown -R nginx:nginx /var/www/super-note
          sudo chmod -R 755 /var/www/super-note
          exit
          EOF

      - name: Install dependencies and run artisan commands
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@13.211.228.65 << 'EOF'
          sudo -u nginx bash << 'INNER_EOF'
          cd /var/www/super-note
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
          INNER_EOF
          EOF