name: Deploy Laravel to EC2

on:
  push:
    branches:
      - master  # Adjust the branch name if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@13.211.228.65 << 'EOF'
          sudo mkdir -p /var/www/super-note-laravel
          sudo chown -R ec2-user:ec2-user /var/www/super-note-laravel
          sudo chmod 775 /var/www/super-note-laravel
          exit
          EOF
          
          scp -r -o StrictHostKeyChecking=no * ec2-user@13.211.228.65:/var/www/super-note-laravel
          scp -r -o StrictHostKeyChecking=no .[!.]* ec2-user@13.211.228.65:/var/www/super-note-laravel
          
          ssh -o StrictHostKeyChecking=no ec2-user@13.211.228.65 << 'EOF'
          sudo chown -R nginx:nginx /var/www/super-note-laravel
          sudo -u nginx bash << 'INNER_EOF'
          cd /var/www/super-note-laravel
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
          INNER_EOF
          EOF